Arrays are fundamental data structures in any programming language. Arrays are similar to lists. The main difference between a list and an array is that all the array elements must be the same data type (they should be all int or float..)

In [1]:
import numpy as np

In [4]:
a=np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
a.shape

(2, 4)

In [7]:
a[1,3]

7

In [9]:
a[1,2]=8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [10]:
a[0]

array([0, 1, 2, 3])

In [11]:
a[1]

array([4, 5, 8, 7])

In [14]:
b=np.array([3,5])
b

array([3, 5])